baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft node app'
primary: true
siteGroup: df674e07-1dac-4435-abe4-85d1ceab6d7b # Craft node app
sortOrder: 1
