dateModified: 1626900441
email:
  fromEmail: maximemasson2@hotmail.com
  fromName: 'Craft node app'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    9311f960-4e69-44b2-aa64-2fedfe0abad2: 'Craft node app' # Craft node app
    342015e1-54e2-41cb-8dda-08558be0fb30: Common # Common
    df674e07-1dac-4435-abe4-85d1ceab6d7b: 'Craft node app' # Craft node app
system:
  edition: solo
  live: true
  name: 'Craft node app'
  schemaVersion: 3.7.7
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
